FROM chromadb/chroma:latest

ENV IS_PERSISTENT=TRUE
ENV PERSIST_DIRECTORY=/chroma/chroma
ENV ANONYMIZED_TELEMETRY=FALSE

EXPOSE 8000

CMD ["run", "--path", "/chroma/chroma", "--host", "0.0.0.0", "--port", "8000"]
